DATA SEGMENT
ARRAY DW 20,30,40,20H,30H,-6
BUFF DB 'ABCD$'
DATA ENDS
CODE SEGMENT
 ASSUME CS:CODE,DS:DATA
START:
 MOV AX, DATA
 MOV DS, AX
 MOV BX, ARRAY+1
 MOV DI, OFFSET ARRAY
 MOV CX, [DI+5]
 MOV DL, BUFF+3
 MOV AH, 4CH
 INT 21H
CODE ENDS
 END START