DATA SEGMENT
	DATA1 db 50 dup(?)
	DATA2 dw 10 dup(0)
	DATA3 dq 5 dup(2 dup(1,2))
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START: MOV AX,DATA
	   MOV DS,AX
	   
	   MOV BX,DATA2
	   MOV AX,LENGTH DATA2
	   MOV CX,SIZE DATA2
	   MOV BX,2
	   MUL BX
	   MOV CX,AX
CODE ENDS
END START