DATA SEGMENT
	MESS1 DB 'COMPUTER SOFTWARE $'
	MESS2 DB 'COMKUTER SOFTWARE $'
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START: MOV AX,DATA
	   MOV DS,AX
	   LEA SI,MESS1
	   MOV ES,AX
	   LEA DI,MESS2
	   MOV CX,19
	   CLD
	   REPE CMPSB
	   JZ EQUAL
	   MOV AH,02H
	   MOV DL,'N'
	   INT 21H
	   JMP FINISH
EQUAL: MOV AH,02H			;注意2号功能是输出DL寄存器中的字符
	   MOV DL,'Y'
	   INT 21H
FINISH:MOV AH,4CH
	   INT 21H
CODE ENDS
END START