DATA SEGMENT
	DA_BY DB 20 DUP(?)
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,ES:DATA
START: MOV AX,DATA
	   MOV ES,AX
	   
	   MOV AL,'Y'
	   LEA DI,DA_BY
	   MOV CX,20
	   CLD
	   
	   REP STOSB			;串存入字符用的指令是STOS

CODE ENDS
END START