DATA SEGMENT
	DA1 DW 21,22,34,0,23,45,23,3,4,4
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START: MOV AX,DATA
	   MOV DS,AX
	   
	   LEA SI,DA1
	   MOV CX,10
	   MOV BX,0
L1:    MOV AX,DS:[SI]
	   ADD SI,2
	   DEC CX
	   CMP AX,0
	   JNZ L1
	   INC BX
	   
	   MOV AX,BX
	   MOV BL,2
	   DIV BL
	   CMP AH,1
	   JNZ FINISH
	   CMP AX,FFFFH   
FINISH:MOV AH,4CH
	   INT 21H
	   
CODE ENDS
END START